Sprint 5. Ревью
vovascool/MovieQuiz-ios pull request #3
Opened 2023-03-28 14:30 UTC by vovascool

Тяжелый спринт, буду заниматься больше)

2023-03-28 16:30 UTC, protos17 requested changes

2023-03-28 16:30 UTC, protos17 commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        let action = {
Сильная ссылка, необходимо добавить weak self

2023-03-28 16:30 UTC, protos17 commented on MovieQuiz/Presentation/AlertPresenter.swift
> +                                   style: .default) { _ in
Сильная ссылка, необходимо добавить weak self

2023-03-28 16:30 UTC, protos17 commented on MovieQuiz/AppDelegate.swift
> +        print("Hello world for my first app!")
Рекомендую удалить, в нем нет необходимости

2023-03-28 16:30 UTC, protos17 commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +            let text = "Ваш результат: \(correctAnswers)/\(questionsAmount)\nКоличество сыгранных квизов: \(statisticService!.gamesCount)\nРекорд: \(statisticService!.bestGame.correct)/\(statisticSer
Рекомендую использовать многострочный вариант строки

2023-03-28 16:30 UTC, protos17 commented on MovieQuiz/Models/QuizQuestion.swift
> +    let text: String
Строка вопроса повторяется, лучше ее написать сразу здесь

2023-03-28 16:30 UTC, protos17 commented on MovieQuiz/Services/QuestionFactory.swift
> +        let question = questions[safe: index]
Рекомендую добавить проверку, не показывался ли уже этот вопрос

2023-04-03 18:40 UTC, protos17 approved these changes

2023-04-03 18:40 UTC, protos17 commented on MovieQuiz/Services/QuestionFactory.swift
> +
Самый простой вариант - добавить здесь проверку, чтобы обнулять массив при заполнении:
if usedIndexes.count >= 10 {
            usedIndexes.removeAll()
        }

2023-04-03 18:40 UTC, protos17 commented on MovieQuiz/Services/QuestionFactory.swift
> +    // никак не получается реализовать функцию случайного выбора из оставшихся вопросов - кнопка сыграть еще раз на алерте ломается, приложение не перезапускается - никак не могу понять в чем дело
Не зубудь удалить лишний закомментированный код

2023-04-04 19:36 UTC, vovascool commented on MovieQuiz/Services/QuestionFactory.swift
> +
Спасибо за совет, все заработало!)

2023-04-04 19:44 UTC, closed without merging