Sprint 7
vovascool/MovieQuiz-ios pull request #5
Opened 2023-04-30 17:01 UTC by vovascool

Рефакторинг был самым сложным, что приходилось делать. Пришлось переписывать многие участки кода, менял свои "костыли" на нормальный код)

2023-05-01 07:29 UTC, IBDesignable requested changes
С тестами все прекрасно! Рефакторинг был сложный, пропустил пару моментов, которые предлагаю обдумать и доработать. 
Ты на правильном пути, работа понравилась)

2023-05-01 07:29 UTC, IBDesignable commented on MovieQuiz/Presentation/MovieQuizPresenter.swift
> +}
очень хорошо разбито по функциям

2023-05-01 07:29 UTC, IBDesignable commented on MovieQuiz/Presentation/MovieQuizPresenter.swift
> +    private var correctAnswers: Int = 0
Это кодстайловый коммент, но чаще стремятся упрощать конструкции, например здесь инт вычислимый тип, и его объявлять не обязательно. Тогда запись будет короче.

2023-05-01 07:29 UTC, IBDesignable commented on MovieQuiz/Presentation/MovieQuizPresenter.swift
> +        questionFactory = QuestionFactory(delegate: self, moviesLoader: MoviesLoader())
На нашем этапе ничего про DI стараемся не говорить, концепция не проста, но если интересно можно познакомиться [с ключевыми словами здесь](https://habr.com/ru/companies/tinkoff/articles/546360/) 

Смотри что здесь хорошо: хорошо что у сервисов, фабрики и презентера есть зависимости и они определены в ините. Не хорошо здесь то, что внутри презентера сервисы собираются, по идее это не ответсвтенность презентера собирать сервисы и фабрики – их нужно получать в инициализаторе.

Обычно для этого существует специальный класс, который умеет создавать нужные зависимости и собирать презентер (или целый экранный модуль).

Пока DI нам неизвестен – такое решение ок, но здесь можно лучше: как минимум создавать StatisticServiceImplementation, QuestionFactory, перед созданием MovieQuizPresenter и передавать их в презентер по протоколу.

2023-05-01 07:29 UTC, IBDesignable commented on MovieQuiz/Presentation/MovieQuizPresenter.swift
> +        }
круто что используешь короткую версию

2023-05-01 07:29 UTC, IBDesignable commented on MovieQuiz/Presentation/MovieQuizPresenter.swift
> +        viewController.showLoadingIndicator()
обычно принято в другом порядке запускать: сначала мы показываем пользователю, что началась долгая операция (пропеллер, блокирующий UI), затем начинаем эту операцию. Когда она закончится – мы убираем пропеллер.

В нашем случае, ошибки нет, так как мы знаем реализацию loadData - асинхронная задача, и проблема не заметна. Но если бы loadData делала тяжелую операцию на главном потоке синхронно, то приложение могло "повиснуть" и перестать отвечать на действия пользователя, и дождалось бы выполнения loadData, и только потом отработал бы showLoadingIndicator.

Рекомендую поменять местами строки

2023-05-01 07:29 UTC, IBDesignable commented on MovieQuiz/Presentation/MovieQuizPresenter.swift
> +        let resultMessage = components.joined(separator: "\n")
вместо joined, можно было использовать еще и [многострочный вариант строки](https://www.swiftbysundell.com/tips/multiline-string-literal-tips-and-tricks/):
```
let textDog = """
╥━━━━━━━━╭━━╮━━┳
╢╭╮╭━━━━━┫┃▋▋━▅┣
╢┃╰┫┈┈┈┈┈┃┃┈┈╰┫┣
╢╰━┫┈┈┈┈┈╰╯╰┳━╯┣
╢┊┊┃┏┳┳━━┓┏┳┫┊┊┣
╨━━┗┛┗┛━━┗┛┗┛━━┻
"""
```

2023-05-01 07:29 UTC, IBDesignable commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        imageView.layer.masksToBounds = true
это свойство можно настроить один раз во viewDidLoad или на сториборде, не обязательно на каждый вызов этой функции свойство обновлять (оно ничем другим не меняется)

2023-05-01 07:29 UTC, IBDesignable commented on MovieQuiz/Presentation/MovieQuizViewController.swift
>          }
очень странная логика в этом методе – если блокируешь, то должно быть однозначно isEnabled = false. 

Любая логика теперь должна слкадываться на плечи презентера. 

Если тебе нужно разблокировать кнопки, то лучше явно отдельный метод под  это завести

Это место нужно исправить, так как нарушает прицнипы архитектуры

2023-05-01 07:29 UTC, IBDesignable commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        let alert = AlertPresenter()
алерт презентер стоит создать один раз, на старте и сохранить в свойство контроллера. По необходимости передавать ему новую модель. С точки зрения архитектуры, метод showNetworkError должен принять уже подготовленную презентером AlertModel, а не message. ( и замыкание сам пусть создает). А вью контроллеру останется вызвать метод `alert.show(view: self, alertModel: alertModel)`

Не исключаю, что в учебнике могли для упращения дать такой пример, но настаиваю, что этот пункт надо доработать.

2023-05-01 07:29 UTC, IBDesignable commented on MovieQuiz/Services/NetworkClient.swift
> +    func fetch(url: URL, handler: @escaping (Result<Data, Error>) -> Void) {
давай договоримся здесь и в следующих проектах: между объектами оставлять максимум одну пустую строчку. 

Нам (разработчикам) платят за аккуратный и удобный код, а не за количество строчек написанных за день :) поэтому давай стремиться писать аккуратно.

2023-05-01 07:29 UTC, IBDesignable commented on MovieQuiz/Services/NetworkClient.swift
> +                            """.data(using: .utf8) ?? Data()
есть ощущение что здесь табов слишком много, и надо поправить отступы. (control+i на выделенном участке должен помочь)

2023-05-01 07:29 UTC, IBDesignable commented on MovieQuiz/Services/QuestionFactory.swift
>                  print("Failed to load image")
обидно, что обработка ошибки удалена, было очень даже хорошо. Правда не хватало return, чтобы правильно выйти из функции

2023-05-01 07:32 UTC, IBDesignable commented
Еще обрати внимание на белую полоску сверху, launch screen сверстан неверно, нужно поправить content mode у картинки

<img width="314" alt="Снимок экрана 2023-05-01 в 10 32 27" src="https://user-images.githubusercontent.com/121577115/235423326-1926bde9-2ab9-4e38-a399-fb898ff4c878.png">

2023-05-04 14:15 UTC, vovascool commented on MovieQuiz/Presentation/MovieQuizViewController.swift
>          }
Блокировку кнопок сделал

2023-05-04 14:16 UTC, vovascool commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        let alert = AlertPresenter()
Здесь совсем не понимаю как вынести в алертпрезентер и потом просто вызывать метод. Наставники не отвечают, а если не отправлю все то отправят в академ. Если сейчас не получится сделать, то обязательно вернусь к задаче - ведь это приложение будет в моем портфолио, я его не заброшу)

2023-05-04 19:15 UTC, IBDesignable commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        let alert = AlertPresenter()
Нужно сделать следующие шаги:

1) сделать строчку в качестве переменной класса вью-контроллера `private let alertPresenter = AlertPresenter()`
2) весь код, который создает AlertModel убрать в MovieQuizPresenter. Вью-контроллеру добавить метод: showAlert(model: AlertModel).
3) реализация showAlert(model) будет проста: alertPresenter.present(model: model)  (примерно такой интерфейс). 
4) реализовать в местах получения текста ошибки, и формирования сообщения о выигрыше alertModel. и вызвать viewController.showAlert(model: alertModel). 

Это все.

2023-05-07 19:19 UTC, merged